apiVersion: apps/v1
kind: Deployment
metadata:
  name: p9-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p9-react-app
  template:
    metadata:
      labels:
        app: p9-react-app
        version: 1.0.1
    spec:
      containers:
        - name: p9-react-app
          image: stevenduckaert/gitops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: p9-react-app
spec:
  type: LoadBalancer
  selector:
    app: p9-react-app
  ports:
   - port: 80
     targetPort: 80